### ISSUE TITLE
`internaldocument.NewDocumentMarshaler` not declared by package

### ISSUE THREAD

**Issue by jabalsad** [aws/smithy-go#342]
Hi,

I generated Go types from smithy models. One member shape uses the `Document` type. The generated code doesn't seem to compile:

In file: codegen/document/document.go:
```
func NewLazyDocument(v interface{}) Interface {
	return internaldocument.NewDocumentMarshaler(v)
}
```

I get an error: `NewDocumentMarshaler not declared by package document`

Any ideas?

**Comment by skmcgrail** [comment]
The first thing that comes to mind is whether you are missing protocol generator implementation? For example are you trying to use the code generator for just generating the Go types, but not implementing any specific protocol serde?

**Comment by jabalsad** [comment]
Yes, that might be it. I am just trying to generate the Go types from the smithy spec.

**Comment by aknuds1** [comment]
I have the same problem after upgrading to smithy-go@main. @skmcgrail do you mean one has to go to specific steps to implement some protocol serde?

**Comment by jabalsad** [comment]
@skmcgrail can you perhaps elaborate what it is we need to do here? thanks.

**Comment by aknuds1** [comment]
I have understood a bit more by reverse engineering (aws-sdk-go-v2](https://github.com/aws/aws-sdk-go-v2), but I haven't got it working yet. Hopefully I'll reach a working solution, and can then share my findings.

**Comment by jabalsad** [comment]
> The first thing that comes to mind is whether you are missing protocol generator implementation? For example are you trying to use the code generator for just generating the Go types, but not implementing any specific protocol serde?

@skmcgrail I'm not exactly sure how to work around this issue. The only protocol we are declaring is:
```
@restJson1
service MyService { ... }
```

And yes - I'm simply trying to generate the Go types, which cannot compile due to the error.

**Comment by jabalsad** [comment]
Update: we're also trying to use the go client, which contains no serializing/deserializing logic. Any advice here would be useful, thanks.

**Comment by jasdel** [comment]
This most likely is related to https://github.com/aws/smithy-go/issues/354 with `smithy-go`'s lack of protocols.

**Comment by jabalsad** [comment]
Ran into this issue in the Go AWS SDK here: 
https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/identitystore@v1.15.7/types#UniqueAttribute

How are we supposed to use this type even in the Go SDK?

**Comment by lucix-aws** [comment]
#458
