### ISSUE TITLE
Generated client does not honor @http trait

### ISSUE THREAD

**Issue by jabalsad** [aws/smithy-go#355]
Hello,

We define our HTTP endpoints using the `@http` trait on operations, e.g.:

```
@http(uri: "/create_account", method: "POST")
operation CreateAccount {
...
```

Taken from https://awslabs.github.io/smithy/1.0/spec/core/http-traits.html

But these paths are nowhere to be found in the generated go client.

**Comment by jasdel** [comment]
This issue is similar to https://github.com/aws/smithy-go/issues/354. Since the `smithy-go` codegen does not include any protocols implementation it cannot understand the `@http` trait. Lets use #354 to track this general concept and feature request.
