### ISSUE TITLE
enhancement: Option to generate a go.mod file

### ISSUE THREAD

**Issue by NukaCody** [aws/smithy-go#373]
We have a folder structure like this:

```
.
├── model
│   ├── build/smithyprojections/model/source/go-codegen
└── externalLib
```

It's a monorepo where externalLib has a `go.mod` file.

```
require github.com/sharedLib v0.0.0

replace github.com/sharedLib => ../model/build/smithyprojections/model/source/go-codegen
```

Maybe a PEBKAC problem, but the import wouldn't work unless we went into the `go-codegen/` and manually created a `go.mod` file.

If this makes sense to add, I'd be happy to make a pull request if you could point me in the general direction. My thinking is either do it by default or by adding an opt-in option in `smithy-build.json`

**Comment by jasdel** [comment]
Thanks for reaching out @NukaCody. Could you go into more details about the use case you're looking to address?

Are you looking for the ability to add additional dependencies to the client generated by smithy-go? Or add the generate client as a dependency to a separate `externalLib` go module in your repository?

Or is this an issue that the generate client is within the `model/build/smithyprojections/model/source/go-codegen` directory and you want to add a go mod replace of `sharedlib` pointing to that folder location? If this is the case we've recently updated an [upstream utility, gomodgen](https://github.com/awslabs/aws-go-multi-module-repository-tools/blob/ca714c205071/cmd/gomodgen/main.go) used by `smithy-go` to support generating a `go.mod` file for the generated output. PR [#381](https://github.com/aws/smithy-go/pull/381) added [generation of Go module in codegen unit tests](https://github.com/aws/smithy-go/blob/176bb649faead4696a08becd233c51720b869b6a/codegen/smithy-go-codegen/src/test/java/software/amazon/smithy/go/codegen/TestUtils.java#L141-L155).

You could update your project's Gradle build tasks to execute the `gomodgen` command to initialize the generated client as a Go module.

```sh
go run \
github.com/awslabs/aws-go-multi-module-repository-tools/cmd/gomodgen@latest \
--build <path relative to gradle project>/model/build/smithyprojections/model/source \
--plugin-dir go-codegen \
--copy-artifact=false \
-prepare-target-dir=false
```

**Comment by NukaCody** [comment]
Yep yep @jasdel, the recent PR solves the exact use case. Thanks so much!
