### ISSUE TITLE
http body need close. Otherwise, it may cause goroutine  leakage in the process

### ISSUE THREAD

**Issue by voctior** [aws/smithy-go#420]
// Body represents the response body.
	//
	// The response body is streamed on demand as the Body field
	// is read. If the network connection fails or the server
	// terminates the response, Body.Read calls return an error.
	//
	// The http Client and Transport guarantee that Body is always
	// non-nil, even on responses without a body or responses with
	// a zero-length body. It is the caller's responsibility to
	// close Body. The default HTTP client's Transport may not
	// reuse HTTP/1.x "keep-alive" TCP connections if the Body is
	// not read to completion and closed.
	//
	// The Body is automatically dechunked if the server replied
	// with a "chunked" Transfer-Encoding.
	//
	// As of Go 1.12, the Body will also implement io.Writer
	// on a successful "101 Switching Protocols" response,
	// as used by WebSockets and HTTP/2's "h2c" mode.
	Body io.ReadCloser

![image](https://user-images.githubusercontent.com/24848992/229741152-0b318d7b-7f5e-476e-bfea-8c9e30b2d386.png)

**Comment by lucix-aws** [comment]
The body close is handled elsewhere in middleware, we shouldn't be leaking anything.
