### ISSUE TITLE
HandleDeserialize Error from MiddleWare

### ISSUE THREAD

**Issue by sathishdv** [aws/smithy-go#557]
while running a high load dealing with DynamoDB with Provisioned Capacity started getting these errors

"github.com/aws/smithy-go/transport/http.(*errorCloseResponseBodyMiddleware).HandleDeserialize(0x41d445?, {0x1d3e698?, 0xc000535d40?}, {{0x170bfa0?, 0xc000535830?}}, {0x1d2e760?, 0xc0054577c0?})" pod=pod_name time=2024-12-06T18:28:49.581311541Z
log="	/build/vendor/github.com/aws/aws-sdk-go-v2/aws/transport/http/response_error_middleware.go:31 +0x53 fp=0xc00288e588 sp=0xc00288e4e0 pc=0xd82093" pod=pod_name time=2024-12-06T18:28:49.581294711Z
This error causing pods to crash and continous restarts.

SDK Version: v1.32.6

Actually the error is from aws/smithy-go 

Based on this thread - https://github.com/aws/aws-sdk-go-v2/issues/1825 looks like the issue is within aws/smith-go

Tried forking and repo (https://github.com/sathishdv/smithy-go) and applied the change as mentioned in the above thread and tried doing high load testing and I didn't see the issue. That seems to fixed it. 
So is this a bug ? or is there any other side-effects with the fix ?

Raised a bug with Go SDK as well - https://github.com/aws/aws-sdk-go-v2/issues/2924

**Comment by lucix-aws** [comment]
https://github.com/aws/aws-sdk-go-v2/issues/2737
